### ISSUE TITLE
运行出错，求助

### ISSUE THREAD

**Issue by sanjinxianfeng** [FenDou1204/SanJinXianFeng#4]
=============================
    *       三晋先锋助手        *
    =============================

Traceback (most recent call last):
  File "sjxf_main.py", line 27, in <module>
    login_msg=SanJinXianFengLoginInfo()
  File "C:\Users\Administrator\Desktop\SanJinXianFeng-main\sjxf_user.py", line 42, in __init__
    self.__GetUserNameFromConf(Path)
  File "C:\Users\Administrator\Desktop\SanJinXianFeng-main\sjxf_user.py", line 46, in __GetUserNameFromConf
    login_msg.read(self.__UserConfPath)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\configparser.py", line 1017, in _read
    for lineno, line in enumerate(fp, start=1):
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 17: illegal multibyte sequence

最后一行是报错的，我应该在哪里修改？

**Comment by FenDou1204** [comment]
重新拉取下代码，再次执行尝试下。

**Comment by sanjinxianfeng** [comment]
再次测试发现问题依旧Traceback (most recent call last):
  File "sjxf_main.py", line 27, in <module>
    login_msg=SanJinXianFengLoginInfo()
  File "C:\Users\Administrator\Desktop\SanJinXianFeng-main\sjxf_user.py", line 4
2, in __init__
    self.__GetUserNameFromConf(Path)
  File "C:\Users\Administrator\Desktop\SanJinXianFeng-main\sjxf_user.py", line 4
6, in __GetUserNameFromConf
    login_msg.read(self.__UserConfPath)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\con
figparser.py", line 697, in read
    self._read(fp, filename)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\con
figparser.py", line 1017, in _read
    for lineno, line in enumerate(fp, start=1):
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 17: illegal m
ultibyte sequence

**Comment by FenDou1204** [comment]
是否有`git pull`最新的代码？其中修改了读取配置文件的编码格式
login_msg.read(self.__UserConfPath, encoding='utf-8')

**Comment by FenDou1204** [comment]
请执行`git pull`或者直接拉取最新分支的代码。查看了昨天的解决方案，其中有地方设置错误。

**Comment by sanjinxianfeng** [comment]
> 请执行`git pull`或者直接拉取最新分支的代码。查看了昨天的解决方案，其中有地方设置错误。

谢谢大神指点帮助，已经成功运行。
